### ISSUE TITLE
Trigger on release

### ISSUE THREAD

**Issue by c-martinez** [gr2m/twitter-together#118]
**What’s missing?**
A trigger to tweet on release.

I would like to have an action which automatically sends a tweet announcing my newest release whenever one make one for example: `Release 1.0.0 of awesome tool is out!`

**Why?**
Tweeting about new releases would be a nice way to keep our user community up to date -- new features, fixed bugs, deprecated functionality, newly introduced bugs...

**Alternatives you tried**
I've tried tweeting myself, but I always forget to do it.

**Comment by gr2m** [comment]
That's a great idea! I think that's out of scope for twitter-together, but there are some other GitHub Actions to send a tweet: https://github.com/marketplace?type=actions&query=tweet

Alternatively, what you could do, is to create a pull request creating a `*.tweet` file each time a new release is created. That way you

1. Won't forget about tweeting
2. Can add some personality to each tweet, instead of having it look the same each time

**Comment by c-martinez** [comment]
Thanks @gr2m -- in the end I used [a different github action](https://github.com/m1ner79/Github-Twittction) to send out tweet, but thanks anyway and good luck with twitter-together!
